### ISSUE TITLE
Error when running default test script

### ISSUE THREAD

**Issue by me-rgb** [MainSilent/Impulse#1]
DevTools listening on ws://127.0.0.1:58716/devtools/browser/45666b07-86a1-4b56-ae92-592ef5b31f05
[75860:37752:0209/190953.243:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.
[75860:37752:0209/190953.243:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
[75860:37752:0209/190953.243:ERROR:chrome_browser_main_extra_parts_metrics.cc(235)] START: GetDefaultBrowser(). If you don't see the END: message, this is crbug.com/1216328.
[75860:84672:0209/190953.245:ERROR:device_event_log_impl.cc(214)] [19:09:53.246] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[75860:84672:0209/190953.245:ERROR:device_event_log_impl.cc(214)] [19:09:53.246] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[75860:37752:0209/190953.251:ERROR:chrome_browser_main_extra_parts_metrics.cc(239)] END: GetDefaultBrowser()
Challenge label: truck
Traceback (most recent call last):
  File "bypass.py", line 8, in <module>
    solver.run()
  File "C:\Users\AdminNoMicrosoft\AppData\Local\Programs\Python\Python38\lib\site-packages\impulse\solver.py", line 35, in run
    self.solve_hcaptcha()
  File "C:\Users\AdminNoMicrosoft\AppData\Local\Programs\Python\Python38\lib\site-packages\impulse\solver.py", line 120, in solve_hcaptcha
    result = direct_prediction(src)
  File "C:\Users\AdminNoMicrosoft\AppData\Local\Programs\Python\Python38\lib\site-packages\impulse\solver.py", line 22, in direct_prediction
    return predict(weights=weights_path, image=image, only_labels=True)
  File "C:\Users\AdminNoMicrosoft\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\AdminNoMicrosoft\AppData\Local\Programs\Python\Python38\lib\site-packages\impulse\yolov5\yolov5.py", line 66, in predict
    image = check_file(image, add_suffix=True if not is_file else False)  # download
  File "C:\Users\AdminNoMicrosoft\AppData\Local\Programs\Python\Python38\Lib\site-packages\impulse\yolov5\utils\general.py", line 324, in check_file
    if Path(file).is_file() or file == '':  # exists
  File "C:\Users\AdminNoMicrosoft\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1402, in is_file
    return S_ISREG(self.stat().st_mode)
  File "C:\Users\AdminNoMicrosoft\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1176, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https:\\imgs.hcaptcha.com\\o\\AbXKe2HG4vYkPCkBbCKfCqz\\w58bZpJeOuepMeARV3WpuK+1HMs76gGGq16PNXyDUnY9Ru4BYmVY2ZSvNwsfDWWPh56ms7f3nJNNaM5nHlfwxnXpj9V+oE\\z3iZp1WZoO+ePvCaF3VcpnfnTV2o+oJaMfyXQKj6XXs85wH8q6S7TpflDlHsQJWCIw=b55VnHeDOjYDKU\\6.png'

**Comment by MainSilent** [comment]
I realized the issue, There was a know bug which escaped the `https://` to `https:/`, What version of chrome are you using?

**Comment by me-rgb** [comment]
98, I also had to update chromedriver, should I use a diff one?

**Comment by MainSilent** [comment]
The issue is on the last part of the error `OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https:\imgs.hcaptcha.com\o\AbXKe2HG4vYkPCkBbCKfCqz\w58bZpJeOuepMeARV3WpuK+1HMs76gGGq16PNXyDUnY9Ru4BYmVY2ZSvNwsfDWWPh56ms7f3nJNNaM5nHlfwxnXpj9V+oE\z3iZp1WZoO+ePvCaF3VcpnfnTV2o+oJaMfyXQKj6XXs85wH8q6S7TpflDlHsQJWCIw=b55VnHeDOjYDKU\6.png'`

The URL should be `https://` instead of `http:\`, I didn't test it on windows, I'll work on an update and let you know when it's ready.

**Comment by MainSilent** [comment]
Can you send more details about the environment? Does this error always happen?
I test it on windows 10 and it worked fine using chrome 98

**Comment by me-rgb** [comment]
https://youtu.be/x8LbTSv5MiQ heres a video of the system info chrome info and me starting the script

**Comment by MainSilent** [comment]
Can you try opening the image url? If it showed `Invalid URI` try removing the extra back slashes except the protocol.

**Comment by MainSilent** [comment]
I'm not able to produce this error on my windows 10 VM with python version `3.9.10`, The issue is from `check_file` function in `general.py` In my understanding it should be easy to solve since it's just different URI behavior on your machine, Let me know if you were able to solve the issue.

**Comment by me-rgb** [comment]
When I open the image url it says Invalid URI from:
https:\\imgs.hcaptcha.com\\kU7hrEndLJgwhoadRBI7RdgdnBjC8M28Qnqp1PTjbyqGpmZklpRbmqRLDbR6NJA4J0CrOxgR1iU0drLsEUomDM1klU+T4tlLnKXuVxjsk77hpaOiMeaqiiyZhfmv+fLw6m5gddTO9V7aFBw3exIYw6DrCzM9X7Qh8S2aN3y+0bDZWpkGOCNYeJrFThM=dowafRTcIe3Sd7Wl.png

https://imgs.hcaptcha.com\\kU7hrEndLJgwhoadRBI7RdgdnBjC8M28Qnqp1PTjbyqGpmZklpRbmqRLDbR6NJA4J0CrOxgR1iU0drLsEUomDM1klU+T4tlLnKXuVxjsk77hpaOiMeaqiiyZhfmv+fLw6m5gddTO9V7aFBw3exIYw6DrCzM9X7Qh8S2aN3y+0bDZWpkGOCNYeJrFThM=dowafRTcIe3Sd7Wl.png

https://imgs.hcaptcha.com//kU7hrEndLJgwhoadRBI7RdgdnBjC8M28Qnqp1PTjbyqGpmZklpRbmqRLDbR6NJA4J0CrOxgR1iU0drLsEUomDM1klU+T4tlLnKXuVxjsk77hpaOiMeaqiiyZhfmv+fLw6m5gddTO9V7aFBw3exIYw6DrCzM9X7Qh8S2aN3y+0bDZWpkGOCNYeJrFThM=dowafRTcIe3Sd7Wl.png
do the same thing

**Comment by MainSilent** [comment]
You also need to remove extra slashes except the protocol, For example the `https://test//sdfsdf//asdasd` to `https://test/sdfsdf/asdasd`, The issue is only from the image url, BTW the images will remove after 5 minutes.

**Comment by me-rgb** [comment]
https://imgs.hcaptcha.com/kU7hrEndLJgwhoadRBI7RdgdnBjC8M28Qnqp1PTjbyqGpmZklpRbmqRLDbR6NJA4J0CrOxgR1iU0drLsEUomDM1klU+T4tlLnKXuVxjsk77hpaOiMeaqiiyZhfmv+fLw6m5gddTO9V7aFBw3exIYw6DrCzM9X7Qh8S2aN3y+0bDZWpkGOCNYeJrFThM=dowafRTcIe3Sd7Wl.png doesnt work, is this uri right? can you send en example?

**Comment by MainSilent** [comment]
Can you try with python version 3.9.10?

**Comment by MainSilent** [comment]
Is your issue solved?

**Comment by me-rgb** [comment]
yes. thank you for the help.

**Comment by me-rgb** [comment]
Question, is this possible to do with reCaptcha? a lot more sites use it

**Comment by MainSilent** [comment]
ReCaptcha uses some more labels that are not currently in the model like crosswalks, chimneys and etc.
It is possible to use the labels that are available but to automate and extract the data from ReCaptcha is more challenging and not stable, You are able to contribute to this project.

**Comment by MainSilent** [comment]
> Excuse me, I'm still having this error, what is the right way to solve it ?

It appears for `me-rgb` upgrading to python `3.9.10` has solved the issue, Did it work for you?

**Comment by MedNewton** [comment]
the problem I had : 
I had python 3.10, and I couldn't install impulse becaue of torch that couldn't be installed for some reason. I downgraded to python 3.8.6 and installed it succefully, but now after the succeful installation, it doesn't work and generates this error.

**Comment by MainSilent** [comment]
> the problem I had : I had python 3.10, and I couldn't install impulse becaue of torch that couldn't be installed for some reason. I downgraded to python 3.8.6 and installed it succefully, but now after the succeful installation, it doesn't work and generates this error.

I encountered the pytorch issue, Not sure how I solved it but it has explained in the error message, I guess it was `Installing C++ Redistributable 2015-2022`

**Comment by climaxxx2** [comment]
Hi mainsilent. This repo is closed. https://github.com/MainSilent/hCaptcha-Bypass its possible to get a firefox version of that? I ve tryed but with no luck. Sorry if i write here. Thanks anyway.

**Comment by MainSilent** [comment]
@climaxxx2 That project based on my last try is obsolete and not working.

**Comment by climaxxx2** [comment]
> @climaxxx2 That project based on my last try is obsolete and not working.

I ve tryed and its working 😱 i get the token
