### ISSUE TITLE
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by Borlp** [MainSilent/Impulse#8]
Challenge label: bus
Traceback (most recent call last):
  File "c:\Users\Jwuhw\Desktop\projekt one\mac.py", line 12, in <module>
    solver.run()
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\impulse\solver.py", line 
35, in run
    self.solve_hcaptcha()
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\impulse\solver.py", line 
120, in solve_hcaptcha
    result = direct_prediction(src)
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\impulse\solver.py", line 
22, in direct_prediction
    return predict(weights=weights_path, image=image, only_labels=True)
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\impulse\yolov5\yolov5.py", line 110, in predict
    pred = model(im, augment=augment, visualize=visualize)
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\impulse\yolov5\models\common.py", line 397, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\impulse\yolov5\models\yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\impulse\yolov5\models\yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "C:\Users\Jwuhw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
PS C:\Users\Jwuhw\Desktop\projekt one> [13144:20420:0625/163934.326:ERROR:util.cc(127)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
[704:20116:0625/164034.364:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by MainSilent** [comment]
This appears to be google drive issue.
